# Generated by Django 5.1.4 on 2024-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourtName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('OpeningHours', models.TimeField()),
                ('ClosingHours', models.TimeField()),
            ],
        ),
    ]
