# Generated by Django 5.1.4 on 2025-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourtName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('OpeningHours', models.TimeField()),
                ('ClosingHours', models.TimeField()),
                ('Active', models.BooleanField(default=True)),
                ('CourtType', models.CharField(choices=[('Single', 'Sân Đơn'), ('Double', 'Sân Đôi')], max_length=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
