# Generated by Django 5.1.4 on 2025-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='ClosingHours',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='OpeningHours',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
