# Generated by Django 5.1.4 on 2025-01-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0002_alter_court_closinghours_alter_court_openinghours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='Price',
        ),
        migrations.AddField(
            model_name='court',
            name='WeekdayPrice',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='WeekendPrice',
            field=models.DecimalField(decimal_places=3, default=150, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='court',
            name='ClosingHours',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='OpeningHours',
            field=models.TimeField(),
        ),
    ]
