# Generated by Django 5.1.5 on 2025-01-20 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
