# Generated by Django 5.1.5 on 2025-01-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0003_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
