# Generated by Django 5.1.5 on 2025-01-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0006_schedule_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=20),
        ),
    ]
