# Generated by Django 5.1.5 on 2025-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0007_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
