# Generated by Django 5.1.5 on 2025-02-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_Court_Mng', '0008_schedule_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending Payment')], default='pending', max_length=20),
        ),
    ]
